name: CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  issue_comment:
    types:
      - created
      - edited
jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ (github.event.issue.pull_request && github.event.comment.body == '/retest') || (github.event.action == 'opened') || (github.event.action == 'synchronize')) }}
    steps:
      - uses: hmarr/debug-action@v2
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: sbt
      - name: Build and Test
        run: sbt -v +test
