name: CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  issue_comment:
    types:
      - created
      - edited
jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ (github.event.issue.pull_request && github.event.comment.body == '/retest') || (github.event.action == 'opened') || (github.event.action == 'synchronize') || (github.event_name == 'push') }}
    steps:
      - uses: hmarr/debug-action@v2
      - name: Figure out the branch
        env:
          PR_URL: ${{github.event.comment.issue.pull_request.url}}
          HEAD_REF: ${{ github.head_ref }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -ex
          if [ -z "$PR_URL" ]; then 
            echo "PR_BRANCH=$HEAD_REF" >> $GITHUB_ENV
          else
            MY_PR_URL=$PR_URL
            PR=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" $MY_PR_URL)
            PR_BRANCH=$(echo $PR | jq .head.ref)
            echo "PR_BRANCH=$PR_BRANCH" >> $GITHUB_ENV
          fi
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ env.PR_BRANCH }}
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: sbt
      - name: Build and Test
        run: sbt -v +test
